ESX = nil
Citizen.CreateThread(function()
	while ESX == nil do
		TriggerEvent('Sneakyesx:getSharedObject', function(obj) ESX = obj end)
		Citizen.Wait(10)
    end
end)
SneakyEvent = TriggerServerEvent

local TattooShop = {
    Position = {
        {
            pos = vector3(-1153.9765625,-1425.6508789063,4.9544591903687),
            blip = {
                label = "Salons de tatouages", 
                ID = 75, 
                Color = 1
            },
        },
        {
            pos = vector3(1322.9339599609,-1651.7247314453,52.275100708008),
            blip = {
                label = "Salons de tatouages", 
                ID = 75, 
                Color = 1
            },
        },
        {
            pos = vector3(322.47463989258,181.18678283691,103.5865020752),
            blip = {
                label = "Salons de tatouages", 
                ID = 75, 
                Color = 1
            },
        },
        {
            pos = vector3(-3170.6804199219,1075.3693847656,20.829183578491),
            blip = {
                label = "Salons de tatouages", 
                ID = 75, 
                Color = 1
            },
        },
        {
            pos = vector3(1864.1744384766,3748.1657714844,33.031852722168),
            blip = {
                label = "Salons de tatouages", 
                ID = 75, 
                Color = 1
            },
        },
        {
            pos = vector3(-294.1257019043,6199.6538085938,31.488185882568),
            blip = {
                label = "Salons de tatouages", 
                ID = 75, 
                Color = 1
            },
        },
    },
    TattooList = {

        mpbusiness_overlays = {
            {nameHash = 'MP_Buis_M_Neck_000', price = 100},
            {nameHash = 'MP_Buis_M_Neck_001', price = 100},
            {nameHash = 'MP_Buis_M_Neck_002', price = 100},
            {nameHash = 'MP_Buis_M_Neck_003', price = 100},
            {nameHash = 'MP_Buis_M_LeftArm_000', price = 100},
            {nameHash = 'MP_Buis_M_LeftArm_001', price = 100},
            {nameHash = 'MP_Buis_M_RightArm_000', price = 100},
            {nameHash = 'MP_Buis_M_RightArm_001', price = 100},
            {nameHash = 'MP_Buis_M_Stomach_000', price = 100},
            {nameHash = 'MP_Buis_M_Chest_000', price = 100},
            {nameHash = 'MP_Buis_M_Chest_001', price = 100},
            {nameHash = 'MP_Buis_M_Back_000', price = 100},
            {nameHash = 'MP_Buis_F_Chest_000', price = 100},
            {nameHash = 'MP_Buis_F_Chest_001', price = 100},
            {nameHash = 'MP_Buis_F_Chest_002', price = 100},
            {nameHash = 'MP_Buis_F_Stom_000', price = 100},
            {nameHash = 'MP_Buis_F_Stom_001', price = 100},
            {nameHash = 'MP_Buis_F_Stom_002', price = 100},
            {nameHash = 'MP_Buis_F_Back_000', price = 100},
            {nameHash = 'MP_Buis_F_Back_001', price = 100},
            {nameHash = 'MP_Buis_F_Neck_000', price = 100},
            {nameHash = 'MP_Buis_M_Neck_000', price = 100},
            {nameHash = 'MP_Buis_F_RArm_000', price = 100},
            {nameHash = 'MP_Buis_F_LArm_000', price = 100},
            {nameHash = 'MP_Buis_M_Neck_003', price = 100},
            {nameHash = 'MP_Buis_F_LLeg_000', price = 100},
            {nameHash = 'MP_Buis_F_RLeg_000', price = 100},
            {nameHash = 'MP_Male_Crew_Tat_000', price = 100},
            {nameHash = 'MP_Male_Crew_Tat_001', price = 100},
            {nameHash = 'MP_Female_Crew_Tat_000', price = 100},
            {nameHash = 'MP_Female_Crew_Tat_001', price = 100},
            {nameHash = 'FM_Bus_F_Hair_a', price = 100},
            {nameHash = 'FM_Bus_F_Hair_b', price = 100},
            {nameHash = 'FM_Bus_F_Hair_c', price = 100},
            {nameHash = 'FM_Bus_F_Hair_d', price = 100},
            {nameHash = 'FM_Bus_F_Hair_e', price = 100},
            {nameHash = 'FM_Bus_M_Hair_000_a', price = 100},
            {nameHash = 'FM_Bus_M_Hair_000_b', price = 100},
            {nameHash = 'FM_Bus_M_Hair_000_c', price = 100},
            {nameHash = 'FM_Bus_M_Hair_000_d', price = 100},
            {nameHash = 'FM_Bus_M_Hair_000_e', price = 100},
            {nameHash = 'FM_Bus_M_Hair_001_a', price = 100},
            {nameHash = 'FM_Bus_M_Hair_001_b', price = 100},
            {nameHash = 'FM_Bus_M_Hair_001_c', price = 100},
            {nameHash = 'FM_Bus_M_Hair_001_d', price = 100},
            {nameHash = 'FM_Bus_M_Hair_001_e', price = 100}
        },

        mphipster_overlays = {
            {nameHash = 'FM_Hip_M_Tat_000', price = 100},
            {nameHash = 'FM_Hip_M_Tat_001', price = 100},
            {nameHash = 'FM_Hip_M_Tat_002', price = 100},
            {nameHash = 'FM_Hip_M_Tat_003', price = 100},
            {nameHash = 'FM_Hip_M_Tat_004', price = 100},
            {nameHash = 'FM_Hip_M_Tat_005', price = 100},
            {nameHash = 'FM_Hip_M_Tat_006', price = 100},
            {nameHash = 'FM_Hip_M_Tat_007', price = 100},
            {nameHash = 'FM_Hip_M_Tat_008', price = 100},
            {nameHash = 'FM_Hip_M_Tat_009', price = 100},
            {nameHash = 'FM_Hip_M_Tat_010', price = 100},
            {nameHash = 'FM_Hip_M_Tat_011', price = 100},
            {nameHash = 'FM_Hip_M_Tat_012', price = 100},
            {nameHash = 'FM_Hip_M_Tat_013', price = 100},
            {nameHash = 'FM_Hip_M_Tat_014', price = 100},
            {nameHash = 'FM_Hip_M_Tat_015', price = 100},
            {nameHash = 'FM_Hip_M_Tat_016', price = 100},
            {nameHash = 'FM_Hip_M_Tat_017', price = 100},
            {nameHash = 'FM_Hip_M_Tat_018', price = 100},
            {nameHash = 'FM_Hip_M_Tat_019', price = 100},
            {nameHash = 'FM_Hip_M_Tat_020', price = 100},
            {nameHash = 'FM_Hip_M_Tat_021', price = 100},
            {nameHash = 'FM_Hip_M_Tat_022', price = 100},
            {nameHash = 'FM_Hip_M_Tat_023', price = 100},
            {nameHash = 'FM_Hip_M_Tat_024', price = 100},
            {nameHash = 'FM_Hip_M_Tat_025', price = 100},
            {nameHash = 'FM_Hip_M_Tat_026', price = 100},
            {nameHash = 'FM_Hip_M_Tat_027', price = 100},
            {nameHash = 'FM_Hip_M_Tat_028', price = 100},
            {nameHash = 'FM_Hip_M_Tat_029', price = 100},
            {nameHash = 'FM_Hip_M_Tat_030', price = 100},
            {nameHash = 'FM_Hip_M_Tat_031', price = 100},
            {nameHash = 'FM_Hip_M_Tat_032', price = 100},
            {nameHash = 'FM_Hip_M_Tat_033', price = 100},
            {nameHash = 'FM_Hip_M_Tat_034', price = 100},
            {nameHash = 'FM_Hip_M_Tat_035', price = 100},
            {nameHash = 'FM_Hip_M_Tat_036', price = 100},
            {nameHash = 'FM_Hip_M_Tat_037', price = 100},
            {nameHash = 'FM_Hip_M_Tat_038', price = 100},
            {nameHash = 'FM_Hip_M_Tat_039', price = 100},
            {nameHash = 'FM_Hip_M_Tat_040', price = 100},
            {nameHash = 'FM_Hip_M_Tat_041', price = 100},
            {nameHash = 'FM_Hip_M_Tat_042', price = 100},
            {nameHash = 'FM_Hip_M_Tat_043', price = 100},
            {nameHash = 'FM_Hip_M_Tat_044', price = 100},
            {nameHash = 'FM_Hip_M_Tat_045', price = 100},
            {nameHash = 'FM_Hip_M_Tat_046', price = 100},
            {nameHash = 'FM_Hip_M_Tat_047', price = 100},
            {nameHash = 'FM_Hip_M_Tat_048', price = 100},
            {nameHash = 'FM_Hip_F_Tat_000', price = 100},
            {nameHash = 'FM_Hip_F_Tat_001', price = 100},
            {nameHash = 'FM_Hip_F_Tat_002', price = 100},
            {nameHash = 'FM_Hip_F_Tat_003', price = 100},
            {nameHash = 'FM_Hip_F_Tat_004', price = 100},
            {nameHash = 'FM_Hip_F_Tat_005', price = 100},
            {nameHash = 'FM_Hip_F_Tat_006', price = 100},
            {nameHash = 'FM_Hip_F_Tat_007', price = 100},
            {nameHash = 'FM_Hip_F_Tat_008', price = 100},
            {nameHash = 'FM_Hip_F_Tat_009', price = 100},
            {nameHash = 'FM_Hip_F_Tat_010', price = 100},
            {nameHash = 'FM_Hip_F_Tat_011', price = 100},
            {nameHash = 'FM_Hip_F_Tat_012', price = 100},
            {nameHash = 'FM_Hip_F_Tat_013', price = 100},
            {nameHash = 'FM_Hip_F_Tat_014', price = 100},
            {nameHash = 'FM_Hip_F_Tat_015', price = 100},
            {nameHash = 'FM_Hip_F_Tat_016', price = 100},
            {nameHash = 'FM_Hip_F_Tat_017', price = 100},
            {nameHash = 'FM_Hip_F_Tat_018', price = 100},
            {nameHash = 'FM_Hip_F_Tat_019', price = 100},
            {nameHash = 'FM_Hip_F_Tat_020', price = 100},
            {nameHash = 'FM_Hip_F_Tat_021', price = 100},
            {nameHash = 'FM_Hip_F_Tat_022', price = 100},
            {nameHash = 'FM_Hip_F_Tat_023', price = 100},
            {nameHash = 'FM_Hip_F_Tat_024', price = 100},
            {nameHash = 'FM_Hip_F_Tat_025', price = 100},
            {nameHash = 'FM_Hip_F_Tat_026', price = 100},
            {nameHash = 'FM_Hip_F_Tat_027', price = 100},
            {nameHash = 'FM_Hip_F_Tat_028', price = 100},
            {nameHash = 'FM_Hip_F_Tat_029', price = 100},
            {nameHash = 'FM_Hip_F_Tat_030', price = 100},
            {nameHash = 'FM_Hip_F_Tat_031', price = 100},
            {nameHash = 'FM_Hip_F_Tat_032', price = 100},
            {nameHash = 'FM_Hip_F_Tat_033', price = 100},
            {nameHash = 'FM_Hip_F_Tat_034', price = 100},
            {nameHash = 'FM_Hip_F_Tat_035', price = 100},
            {nameHash = 'FM_Hip_F_Tat_036', price = 100},
            {nameHash = 'FM_Hip_F_Tat_037', price = 100},
            {nameHash = 'FM_Hip_F_Tat_038', price = 100},
            {nameHash = 'FM_Hip_F_Tat_039', price = 100},
            {nameHash = 'FM_Hip_F_Tat_040', price = 100},
            {nameHash = 'FM_Hip_F_Tat_041', price = 100},
            {nameHash = 'FM_Hip_F_Tat_042', price = 100},
            {nameHash = 'FM_Hip_F_Tat_043', price = 100},
            {nameHash = 'FM_Hip_F_Tat_044', price = 100},
            {nameHash = 'FM_Hip_F_Tat_045', price = 100},
            {nameHash = 'FM_Hip_F_Tat_046', price = 100},
            {nameHash = 'FM_Hip_F_Tat_047', price = 100},
            {nameHash = 'FM_Hip_F_Tat_048', price = 100},
            {nameHash = 'FM_Hip_M_Hair_000_a', price = 100},
            {nameHash = 'FM_Hip_M_Hair_000_b', price = 100},
            {nameHash = 'FM_Hip_M_Hair_000_c', price = 100},
            {nameHash = 'FM_Hip_M_Hair_000_d', price = 100},
            {nameHash = 'FM_Hip_M_Hair_000_e', price = 100},
            {nameHash = 'FM_Hip_F_Hair_000_a', price = 100},
            {nameHash = 'FM_Hip_F_Hair_000_b', price = 100},
            {nameHash = 'FM_Hip_F_Hair_000_c', price = 100},
            {nameHash = 'FM_Hip_F_Hair_000_d', price = 100},
            {nameHash = 'FM_Hip_F_Hair_000_e', price = 100},
            {nameHash = 'FM_Hip_M_Hair_001_a', price = 100},
            {nameHash = 'FM_Hip_M_Hair_001_b', price = 100},
            {nameHash = 'FM_Hip_M_Hair_001_c', price = 100},
            {nameHash = 'FM_Hip_M_Hair_001_d', price = 100},
            {nameHash = 'FM_Hip_M_Hair_001_e', price = 100},
            {nameHash = 'FM_Hip_F_Hair_001_a', price = 100},
            {nameHash = 'FM_Hip_F_Hair_001_b', price = 100},
            {nameHash = 'FM_Hip_F_Hair_001_c', price = 100},
            {nameHash = 'FM_Hip_F_Hair_001_d', price = 100},
            {nameHash = 'FM_Hip_F_Hair_001_e', price = 100},
            {nameHash = 'FM_F_Hair_017_a', price = 100},
            {nameHash = 'FM_F_Hair_017_b', price = 100},
            {nameHash = 'FM_F_Hair_017_c', price = 100},
            {nameHash = 'FM_F_Hair_017_d', price = 100},
            {nameHash = 'FM_F_Hair_017_e', price = 100},
            {nameHash = 'FM_F_Hair_020_a', price = 100},
            {nameHash = 'FM_F_Hair_020_b', price = 100},
            {nameHash = 'FM_F_Hair_020_c', price = 100},
            {nameHash = 'FM_F_Hair_020_d', price = 100},
            {nameHash = 'FM_F_Hair_020_e', price = 100},
            {nameHash = 'FM_Disc_M_Hair_001_a', price = 100},
            {nameHash = 'FM_Disc_M_Hair_001_b', price = 100},
            {nameHash = 'FM_Disc_M_Hair_001_c', price = 100},
            {nameHash = 'FM_Disc_M_Hair_001_d', price = 100},
            {nameHash = 'FM_Disc_M_Hair_001_e', price = 100}
            
        },

        mpbiker_overlays = {
            {nameHash = 'MP_Biker_Hair_000_M', price = 100},
            {nameHash = 'MP_Biker_Hair_000_F', price = 100},
            {nameHash = 'MP_Biker_Hair_001_M', price = 100},
            {nameHash = 'MP_Biker_Hair_001_F', price = 100},
            {nameHash = 'MP_Biker_Hair_002_M', price = 100},
            {nameHash = 'MP_Biker_Hair_002_F', price = 100},
            {nameHash = 'MP_Biker_Hair_003_M', price = 100},
            {nameHash = 'MP_Biker_Hair_003_F', price = 100},
            {nameHash = 'MP_Biker_Hair_004_M', price = 100},
            {nameHash = 'MP_Biker_Hair_004_F', price = 100},
            {nameHash = 'MP_Biker_Hair_005_M', price = 100},
            {nameHash = 'MP_Biker_Hair_005_F', price = 100},
            {nameHash = 'MP_Biker_Hair_006_M', price = 100},
            {nameHash = 'MP_Biker_Hair_006_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_000_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_000_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_001_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_001_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_002_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_002_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_003_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_003_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_004_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_004_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_005_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_005_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_006_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_006_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_007_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_007_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_008_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_008_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_009_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_009_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_010_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_010_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_011_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_011_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_012_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_012_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_013_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_013_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_014_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_014_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_015_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_015_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_016_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_016_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_017_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_017_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_018_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_018_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_019_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_019_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_020_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_020_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_021_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_021_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_022_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_022_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_023_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_023_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_024_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_024_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_025_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_025_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_026_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_026_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_027_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_027_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_028_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_028_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_029_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_029_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_030_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_030_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_031_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_031_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_032_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_032_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_033_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_033_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_034_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_034_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_035_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_035_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_036_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_036_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_037_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_037_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_038_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_038_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_039_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_039_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_040_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_040_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_041_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_041_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_042_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_042_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_043_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_043_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_044_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_044_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_045_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_045_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_046_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_046_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_047_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_047_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_048_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_048_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_049_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_049_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_050_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_050_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_051_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_051_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_052_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_052_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_053_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_053_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_054_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_054_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_055_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_055_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_056_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_056_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_057_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_057_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_058_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_058_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_059_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_059_F', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_060_M', price = 100},
            {nameHash = 'MP_MP_Biker_Tat_060_F', price = 100}


        },

        mpairraces_overlays = {
            {nameHash = 'MP_Airraces_Tattoo_000_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_001_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_002_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_003_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_004_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_005_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_006_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_007_M', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_000_F', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_001_F', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_002_F', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_003_F', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_004_F', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_005_F', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_006_F', price = 100},
            {nameHash = 'MP_Airraces_Tattoo_007_F', price = 100}
        },

        mpbeach_overlays = {
            {nameHash = 'MP_Bea_F_Back_000', price = 100},
            {nameHash = 'MP_Bea_F_Back_001', price = 100},
            {nameHash = 'MP_Bea_F_Back_002', price = 100},
            {nameHash = 'MP_Bea_F_Chest_000', price = 100},
            {nameHash = 'MP_Bea_F_Chest_001', price = 100},
            {nameHash = 'MP_Bea_F_Chest_002', price = 100},
            {nameHash = 'MP_Bea_F_RSide_000', price = 100},
            {nameHash = 'MP_Bea_F_RLeg_000', price = 100},
            {nameHash = 'MP_Bea_F_RArm_001', price = 100},
            {nameHash = 'MP_Bea_F_Neck_000', price = 100},
            {nameHash = 'MP_Bea_F_Should_000', price = 100},
            {nameHash = 'MP_Bea_F_Should_001', price = 100},
            {nameHash = 'MP_Bea_F_Stom_000', price = 100},
            {nameHash = 'MP_Bea_F_Stom_001', price = 100},
            {nameHash = 'MP_Bea_F_Stom_002', price = 100},
            {nameHash = 'MP_Bea_F_LArm_000', price = 100},
            {nameHash = 'MP_Bea_F_LArm_001', price = 100},
            {nameHash = 'MP_Bea_M_Back_000', price = 100},
            {nameHash = 'MP_Bea_M_Chest_000', price = 100},
            {nameHash = 'MP_Bea_M_Chest_001', price = 100},
            {nameHash = 'MP_Bea_M_Head_000', price = 100},
            {nameHash = 'MP_Bea_M_Head_001', price = 100},
            {nameHash = 'MP_Bea_M_Head_002', price = 100},
            {nameHash = 'MP_Bea_M_Lleg_000', price = 100},
            {nameHash = 'MP_Bea_M_Rleg_000', price = 100},
            {nameHash = 'MP_Bea_M_RArm_000', price = 100},
            {nameHash = 'MP_Bea_M_LArm_000', price = 100},
            {nameHash = 'MP_Bea_M_Neck_000', price = 100},
            {nameHash = 'MP_Bea_M_Neck_001', price = 100},
            {nameHash = 'MP_Bea_M_RArm_001', price = 100},
            {nameHash = 'MP_Bea_M_Stom_000', price = 100},
            {nameHash = 'MP_Bea_M_Stom_001', price = 100},
            {nameHash = 'FM_Hair_Fuzz', price = 100}
        },

        mpchristmas2_overlays = {
            {nameHash = 'MP_Xmas2_M_Tat_000', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_001', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_003', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_004', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_005', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_006', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_007', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_008', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_009', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_010', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_011', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_012', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_013', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_014', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_015', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_016', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_017', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_018', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_019', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_022', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_023', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_024', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_025', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_026', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_027', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_028', price = 100},
            {nameHash = 'MP_Xmas2_M_Tat_029', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_000', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_001', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_003', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_004', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_005', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_006', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_007', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_008', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_009', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_010', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_011', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_012', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_013', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_014', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_015', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_016', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_017', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_018', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_019', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_022', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_023', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_024', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_025', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_026', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_027', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_028', price = 100},
            {nameHash = 'MP_Xmas2_F_Tat_029', price = 100}
        },

        mpgunrunning_overlays = {
            {nameHash = 'MP_Gunrunning_Tattoo_000_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_001_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_002_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_003_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_004_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_005_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_006_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_007_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_008_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_009_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_010_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_011_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_012_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_013_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_014_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_015_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_016_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_017_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_018_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_019_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_020_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_021_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_022_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_023_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_024_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_025_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_026_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_027_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_028_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_029_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_030_M', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_000_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_001_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_002_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_003_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_004_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_005_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_006_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_007_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_008_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_009_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_010_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_011_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_012_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_013_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_014_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_015_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_016_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_017_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_018_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_019_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_020_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_021_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_022_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_023_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_024_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_025_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_026_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_027_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_028_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_029_F', price = 100},
            {nameHash = 'MP_Gunrunning_Tattoo_030_F', price = 100}
        },

        mpimportexport_overlays = {
            {nameHash = 'MP_MP_ImportExport_Tat_000_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_001_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_002_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_003_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_004_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_005_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_006_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_007_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_008_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_009_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_010_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_011_M', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_000_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_001_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_002_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_003_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_004_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_005_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_006_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_007_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_008_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_009_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_010_F', price = 100},
            {nameHash = 'MP_MP_ImportExport_Tat_011_F', price = 100}
        },

        mplowrider2_overlays = {
            {nameHash = 'MP_LR_Tat_000_M', price = 100},
            {nameHash = 'MP_LR_Tat_003_M', price = 100},
            {nameHash = 'MP_LR_Tat_006_M', price = 100},
            {nameHash = 'MP_LR_Tat_008_M', price = 100},
            {nameHash = 'MP_LR_Tat_011_M', price = 100},
            {nameHash = 'MP_LR_Tat_012_M', price = 100},
            {nameHash = 'MP_LR_Tat_016_M', price = 100},
            {nameHash = 'MP_LR_Tat_018_M', price = 100},
            {nameHash = 'MP_LR_Tat_019_M', price = 100},
            {nameHash = 'MP_LR_Tat_022_M', price = 100},
            {nameHash = 'MP_LR_Tat_028_M', price = 100},
            {nameHash = 'MP_LR_Tat_029_M', price = 100},
            {nameHash = 'MP_LR_Tat_030_M', price = 100},
            {nameHash = 'MP_LR_Tat_031_M', price = 100},
            {nameHash = 'MP_LR_Tat_032_M', price = 100},
            {nameHash = 'MP_LR_Tat_035_M', price = 100},
            {nameHash = 'MP_LR_Tat_000_F', price = 100},
            {nameHash = 'MP_LR_Tat_003_F', price = 100},
            {nameHash = 'MP_LR_Tat_006_F', price = 100},
            {nameHash = 'MP_LR_Tat_008_F', price = 100},
            {nameHash = 'MP_LR_Tat_011_F', price = 100},
            {nameHash = 'MP_LR_Tat_012_F', price = 100},
            {nameHash = 'MP_LR_Tat_016_F', price = 100},
            {nameHash = 'MP_LR_Tat_018_F', price = 100},
            {nameHash = 'MP_LR_Tat_019_F', price = 100},
            {nameHash = 'MP_LR_Tat_022_F', price = 100},
            {nameHash = 'MP_LR_Tat_028_F', price = 100},
            {nameHash = 'MP_LR_Tat_029_F', price = 100},
            {nameHash = 'MP_LR_Tat_030_F', price = 100},
            {nameHash = 'MP_LR_Tat_031_F', price = 100},
            {nameHash = 'MP_LR_Tat_032_F', price = 100},
            {nameHash = 'MP_LR_Tat_035_F', price = 100},
            {nameHash = 'LR_F_Hair_003', price = 100},
            {nameHash = 'LR_F_Hair_004', price = 100},
            {nameHash = 'LR_F_Hair_006', price = 100},
            {nameHash = 'LR_M_Hair_004', price = 100},
            {nameHash = 'LR_M_Hair_005', price = 100},
            {nameHash = 'LR_M_Hair_006', price = 100}
        },

        mplowrider_overlays = {
            {nameHash = 'MP_LR_Tat_001_M', price = 100},
            {nameHash = 'MP_LR_Tat_002_M', price = 100},
            {nameHash = 'MP_LR_Tat_004_M', price = 100},
            {nameHash = 'MP_LR_Tat_005_M', price = 100},
            {nameHash = 'MP_LR_Tat_007_M', price = 100},
            {nameHash = 'MP_LR_Tat_009_M', price = 100},
            {nameHash = 'MP_LR_Tat_010_M', price = 100},
            {nameHash = 'MP_LR_Tat_013_M', price = 100},
            {nameHash = 'MP_LR_Tat_014_M', price = 100},
            {nameHash = 'MP_LR_Tat_015_M', price = 100},
            {nameHash = 'MP_LR_Tat_017_M', price = 100},
            {nameHash = 'MP_LR_Tat_020_M', price = 100},
            {nameHash = 'MP_LR_Tat_021_M', price = 100},
            {nameHash = 'MP_LR_Tat_023_M', price = 100},
            {nameHash = 'MP_LR_Tat_026_M', price = 100},
            {nameHash = 'MP_LR_Tat_027_M', price = 100},
            {nameHash = 'MP_LR_Tat_033_M', price = 100},
            {nameHash = 'MP_LR_Tat_001_F', price = 100},
            {nameHash = 'MP_LR_Tat_002_F', price = 100},
            {nameHash = 'MP_LR_Tat_004_F', price = 100},
            {nameHash = 'MP_LR_Tat_005_F', price = 100},
            {nameHash = 'MP_LR_Tat_007_F', price = 100},
            {nameHash = 'MP_LR_Tat_009_F', price = 100},
            {nameHash = 'MP_LR_Tat_010_F', price = 100},
            {nameHash = 'MP_LR_Tat_013_F', price = 100},
            {nameHash = 'MP_LR_Tat_014_F', price = 100},
            {nameHash = 'MP_LR_Tat_015_F', price = 100},
            {nameHash = 'MP_LR_Tat_017_F', price = 100},
            {nameHash = 'MP_LR_Tat_020_F', price = 100},
            {nameHash = 'MP_LR_Tat_021_F', price = 100},
            {nameHash = 'MP_LR_Tat_023_F', price = 100},
            {nameHash = 'MP_LR_Tat_026_F', price = 100},
            {nameHash = 'MP_LR_Tat_027_F', price = 100},
            {nameHash = 'MP_LR_Tat_033_F', price = 100},
            {nameHash = 'LR_F_Hair_000', price = 100},
            {nameHash = 'LR_F_Hair_001', price = 100},
            {nameHash = 'LR_F_Hair_002', price = 100},
            {nameHash = 'LR_M_Hair_000', price = 100},
            {nameHash = 'LR_M_Hair_001', price = 100},
            {nameHash = 'LR_M_Hair_002', price = 100},
            {nameHash = 'LR_M_Hair_003', price = 100}
        },

        mpchristmas2017_overlays = {
            {nameHash = 'MP_Christmas2017_Tattoo_000_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_000_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_001_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_001_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_002_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_002_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_003_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_003_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_004_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_004_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_005_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_005_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_006_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_006_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_007_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_007_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_008_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_008_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_009_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_009_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_010_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_010_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_011_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_011_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_012_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_012_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_013_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_013_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_014_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_014_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_015_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_015_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_016_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_016_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_017_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_017_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_018_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_018_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_019_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_019_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_020_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_020_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_021_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_021_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_022_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_022_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_023_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_023_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_024_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_024_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_025_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_025_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_026_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_026_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_027_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_027_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_028_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_028_F', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_029_M', price = 100},
            {nameHash = 'MP_Christmas2017_Tattoo_029_F', price = 100}

        },

        mpheist3_overlays = {
            {nameHash = 'mpHeist3_Tat_000_M', price = 100},
            {nameHash = 'mpHeist3_Tat_000_F', price = 100},
            {nameHash = 'mpHeist3_Tat_001_M', price = 100},
            {nameHash = 'mpHeist3_Tat_001_F', price = 100},
            {nameHash = 'mpHeist3_Tat_002_M', price = 100},
            {nameHash = 'mpHeist3_Tat_002_F', price = 100},
            {nameHash = 'mpHeist3_Tat_003_M', price = 100},
            {nameHash = 'mpHeist3_Tat_003_F', price = 100},
            {nameHash = 'mpHeist3_Tat_004_M', price = 100},
            {nameHash = 'mpHeist3_Tat_004_F', price = 100},
            {nameHash = 'mpHeist3_Tat_005_M', price = 100},
            {nameHash = 'mpHeist3_Tat_005_F', price = 100},
            {nameHash = 'mpHeist3_Tat_006_M', price = 100},
            {nameHash = 'mpHeist3_Tat_006_F', price = 100},
            {nameHash = 'mpHeist3_Tat_007_M', price = 100},
            {nameHash = 'mpHeist3_Tat_007_F', price = 100},
            {nameHash = 'mpHeist3_Tat_008_M', price = 100},
            {nameHash = 'mpHeist3_Tat_008_F', price = 100},
            {nameHash = 'mpHeist3_Tat_009_M', price = 100},
            {nameHash = 'mpHeist3_Tat_009_F', price = 100},
            {nameHash = 'mpHeist3_Tat_010_M', price = 100},
            {nameHash = 'mpHeist3_Tat_010_F', price = 100},
            {nameHash = 'mpHeist3_Tat_011_M', price = 100},
            {nameHash = 'mpHeist3_Tat_011_F', price = 100},
            {nameHash = 'mpHeist3_Tat_012_M', price = 100},
            {nameHash = 'mpHeist3_Tat_012_F', price = 100},
            {nameHash = 'mpHeist3_Tat_013_M', price = 100},
            {nameHash = 'mpHeist3_Tat_013_F', price = 100},
            {nameHash = 'mpHeist3_Tat_014_M', price = 100},
            {nameHash = 'mpHeist3_Tat_014_F', price = 100},
            {nameHash = 'mpHeist3_Tat_015_M', price = 100},
            {nameHash = 'mpHeist3_Tat_015_F', price = 100},
            {nameHash = 'mpHeist3_Tat_016_M', price = 100},
            {nameHash = 'mpHeist3_Tat_016_F', price = 100},
            {nameHash = 'mpHeist3_Tat_017_M', price = 100},
            {nameHash = 'mpHeist3_Tat_017_F', price = 100},
            {nameHash = 'mpHeist3_Tat_018_M', price = 100},
            {nameHash = 'mpHeist3_Tat_018_F', price = 100},
            {nameHash = 'mpHeist3_Tat_019_M', price = 100},
            {nameHash = 'mpHeist3_Tat_019_F', price = 100},
            {nameHash = 'mpHeist3_Tat_020_M', price = 100},
            {nameHash = 'mpHeist3_Tat_020_F', price = 100},
            {nameHash = 'mpHeist3_Tat_021_M', price = 100},
            {nameHash = 'mpHeist3_Tat_021_F', price = 100},
            {nameHash = 'mpHeist3_Tat_022_M', price = 100},
            {nameHash = 'mpHeist3_Tat_022_F', price = 100},
            {nameHash = 'mpHeist3_Tat_023_M', price = 100},
            {nameHash = 'mpHeist3_Tat_023_F', price = 100},
            {nameHash = 'mpHeist3_Tat_024_M', price = 100},
            {nameHash = 'mpHeist3_Tat_024_F', price = 100},
            {nameHash = 'mpHeist3_Tat_025_M', price = 100},
            {nameHash = 'mpHeist3_Tat_025_F', price = 100},
            {nameHash = 'mpHeist3_Tat_026_M', price = 100},
            {nameHash = 'mpHeist3_Tat_026_F', price = 100},
            {nameHash = 'mpHeist3_Tat_027_M', price = 100},
            {nameHash = 'mpHeist3_Tat_027_F', price = 100},
            {nameHash = 'mpHeist3_Tat_028_M', price = 100},
            {nameHash = 'mpHeist3_Tat_028_F', price = 100},
            {nameHash = 'mpHeist3_Tat_029_M', price = 100},
            {nameHash = 'mpHeist3_Tat_029_F', price = 100},
            {nameHash = 'mpHeist3_Tat_030_M', price = 100},
            {nameHash = 'mpHeist3_Tat_030_F', price = 100},
            {nameHash = 'mpHeist3_Tat_031_M', price = 100},
            {nameHash = 'mpHeist3_Tat_031_F', price = 100},
            {nameHash = 'mpHeist3_Tat_032_M', price = 100},
            {nameHash = 'mpHeist3_Tat_032_F', price = 100},
            {nameHash = 'mpHeist3_Tat_033_M', price = 100},
            {nameHash = 'mpHeist3_Tat_033_F', price = 100},
            {nameHash = 'mpHeist3_Tat_034_M', price = 100},
            {nameHash = 'mpHeist3_Tat_034_F', price = 100},
            {nameHash = 'mpHeist3_Tat_035_M', price = 100},
            {nameHash = 'mpHeist3_Tat_035_F', price = 100},
            {nameHash = 'mpHeist3_Tat_036_M', price = 100},
            {nameHash = 'mpHeist3_Tat_036_F', price = 100},
            {nameHash = 'mpHeist3_Tat_037_M', price = 100},
            {nameHash = 'mpHeist3_Tat_037_F', price = 100},
            {nameHash = 'mpHeist3_Tat_038_M', price = 100},
            {nameHash = 'mpHeist3_Tat_038_F', price = 100},
            {nameHash = 'mpHeist3_Tat_039_M', price = 100},
            {nameHash = 'mpHeist3_Tat_039_F', price = 100},
            {nameHash = 'mpHeist3_Tat_040_M', price = 100},
            {nameHash = 'mpHeist3_Tat_040_F', price = 100},
            {nameHash = 'mpHeist3_Tat_041_M', price = 100},
            {nameHash = 'mpHeist3_Tat_041_F', price = 100},
            {nameHash = 'mpHeist3_Tat_042_M', price = 100},
            {nameHash = 'mpHeist3_Tat_042_F', price = 100},
            {nameHash = 'mpHeist3_Tat_043_M', price = 100},
            {nameHash = 'mpHeist3_Tat_043_F', price = 100},
            {nameHash = 'mpHeist3_Tat_044_M', price = 100},
            {nameHash = 'mpHeist3_Tat_044_F', price = 100}
        },

        mpheist4_overlays = {
            {nameHash = 'MP_Heist4_Tat_000_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_000_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_001_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_001_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_002_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_002_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_003_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_003_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_004_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_004_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_005_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_005_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_006_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_006_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_007_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_007_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_008_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_008_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_009_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_009_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_010_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_010_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_011_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_011_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_012_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_012_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_013_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_013_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_014_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_014_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_015_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_015_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_016_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_016_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_017_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_017_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_018_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_018_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_019_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_019_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_020_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_020_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_021_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_021_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_022_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_022_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_023_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_023_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_024_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_024_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_025_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_025_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_026_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_026_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_027_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_027_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_028_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_028_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_029_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_029_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_030_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_030_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_031_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_031_F', price = 100},
            {nameHash = 'MP_Heist4_Tat_032_M', price = 100},
            {nameHash = 'MP_Heist4_Tat_032_M', price = 100}
    
        },

        mpluxe2_overlays = {
            {nameHash = 'MP_LUXE_TAT_002_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_005_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_010_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_011_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_012_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_016_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_017_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_018_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_022_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_023_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_025_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_026_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_027_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_028_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_029_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_030_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_031_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_002_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_005_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_010_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_011_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_012_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_016_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_017_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_018_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_022_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_023_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_025_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_026_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_027_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_028_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_029_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_030_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_031_F', price = 100}
        },

        mpluxe_overlays = {
            {nameHash = 'MP_LUXE_TAT_000_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_001_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_003_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_004_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_006_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_007_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_008_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_009_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_013_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_014_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_015_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_019_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_020_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_021_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_024_M', price = 100},
            {nameHash = 'MP_LUXE_TAT_000_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_001_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_003_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_004_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_006_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_007_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_008_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_009_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_013_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_014_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_015_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_019_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_020_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_021_F', price = 100},
            {nameHash = 'MP_LUXE_TAT_024_F', price = 100}
        },

        mpsmuggler_overlays = {
            {nameHash = 'MP_Smuggler_Tattoo_000_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_001_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_002_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_002_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_003_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_003_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_004_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_004_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_005_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_005_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_006_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_006_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_007_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_007_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_008_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_008_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_009_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_009_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_010_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_010_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_011_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_011_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_012_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_012_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_013_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_013_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_014_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_014_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_015_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_015_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_016_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_016_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_017_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_017_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_018_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_018_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_019_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_019_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_020_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_020_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_021_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_021_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_022_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_022_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_023_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_023_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_024_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_024_F', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_025_M', price = 100},
            {nameHash = 'MP_Smuggler_Tattoo_025_F', price = 100}
        },

        mpstunt_overlays = {
            {nameHash = 'MP_MP_Stunt_Tat_000_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_001_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_002_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_003_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_004_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_005_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_006_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_007_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_008_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_009_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_010_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_011_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_012_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_013_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_014_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_015_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_016_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_017_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_018_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_019_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_020_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_021_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_022_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_023_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_024_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_025_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_026_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_027_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_028_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_029_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_030_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_031_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_032_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_033_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_034_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_035_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_036_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_037_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_038_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_039_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_040_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_041_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_042_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_043_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_044_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_045_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_046_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_047_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_048_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_049_M', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_000_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_001_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_002_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_003_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_004_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_005_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_006_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_007_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_008_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_009_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_010_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_011_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_012_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_013_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_014_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_015_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_016_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_017_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_018_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_019_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_020_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_021_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_022_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_023_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_024_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_025_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_026_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_027_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_028_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_029_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_030_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_031_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_032_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_033_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_034_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_035_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_036_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_037_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_038_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_039_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_040_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_041_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_042_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_043_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_044_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_045_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_046_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_047_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_048_F', price = 100},
            {nameHash = 'MP_MP_Stunt_Tat_049_F', price = 100}
        },

        mpvinewood_overlays = {
            {nameHash = 'MP_Vinewood_Hair_M_000_M', price = 100},
            {nameHash = 'MP_Vinewood_Hair_F_000_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_000_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_000_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_001_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_001_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_002_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_002_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_003_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_003_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_004_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_004_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_005_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_005_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_006_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_006_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_007_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_007_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_008_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_008_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_009_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_009_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_010_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_010_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_011_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_011_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_012_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_012_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_013_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_013_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_014_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_014_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_015_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_015_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_016_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_016_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_017_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_017_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_018_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_018_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_019_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_019_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_020_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_020_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_021_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_021_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_022_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_022_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_023_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_023_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_024_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_024_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_025_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_025_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_026_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_026_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_027_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_027_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_028_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_028_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_029_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_029_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_030_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_030_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_031_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_031_F', price = 100},
            {nameHash = 'MP_Vinewood_Tat_032_M', price = 100},
            {nameHash = 'MP_Vinewood_Tat_032_F', price = 100}
           
        },

        multiplayer_overlays = {
            {nameHash = 'FM_Tat_Award_M_000', price = 100},
            {nameHash = 'FM_Tat_Award_M_001', price = 100},
            {nameHash = 'FM_Tat_Award_M_002', price = 100},
            {nameHash = 'FM_Tat_Award_M_003', price = 100},
            {nameHash = 'FM_Tat_Award_M_004', price = 100},
            {nameHash = 'FM_Tat_Award_M_005', price = 100},
            {nameHash = 'FM_Tat_Award_M_006', price = 100},
            {nameHash = 'FM_Tat_Award_M_007', price = 100},
            {nameHash = 'FM_Tat_Award_M_008', price = 100},
            {nameHash = 'FM_Tat_Award_M_009', price = 100},
            {nameHash = 'FM_Tat_Award_M_010', price = 100},
            {nameHash = 'FM_Tat_Award_M_011', price = 100},
            {nameHash = 'FM_Tat_Award_M_012', price = 100},
            {nameHash = 'FM_Tat_Award_M_013', price = 100},
            {nameHash = 'FM_Tat_Award_M_014', price = 100},
            {nameHash = 'FM_Tat_Award_M_015', price = 100},
            {nameHash = 'FM_Tat_Award_M_016', price = 100},
            {nameHash = 'FM_Tat_Award_M_017', price = 100},
            {nameHash = 'FM_Tat_Award_M_018', price = 100},
            {nameHash = 'FM_Tat_Award_M_019', price = 100},
            {nameHash = 'FM_Tat_Award_F_000', price = 100},
            {nameHash = 'FM_Tat_Award_F_001', price = 100},
            {nameHash = 'FM_Tat_Award_F_002', price = 100},
            {nameHash = 'FM_Tat_Award_F_003', price = 100},
            {nameHash = 'FM_Tat_Award_F_004', price = 100},
            {nameHash = 'FM_Tat_Award_F_005', price = 100},
            {nameHash = 'FM_Tat_Award_F_006', price = 100},
            {nameHash = 'FM_Tat_Award_F_007', price = 100},
            {nameHash = 'FM_Tat_Award_F_008', price = 100},
            {nameHash = 'FM_Tat_Award_F_009', price = 100},
            {nameHash = 'FM_Tat_Award_F_010', price = 100},
            {nameHash = 'FM_Tat_Award_F_011', price = 100},
            {nameHash = 'FM_Tat_Award_F_012', price = 100},
            {nameHash = 'FM_Tat_Award_F_013', price = 100},
            {nameHash = 'FM_Tat_Award_F_014', price = 100},
            {nameHash = 'FM_Tat_Award_F_015', price = 100},
            {nameHash = 'FM_Tat_Award_F_016', price = 100},
            {nameHash = 'FM_Tat_Award_F_017', price = 100},
            {nameHash = 'FM_Tat_Award_F_018', price = 100},
            {nameHash = 'FM_Tat_Award_F_019', price = 100},
            {nameHash = 'FM_Tat_M_000', price = 100},
            {nameHash = 'FM_Tat_M_001', price = 100},
            {nameHash = 'FM_Tat_M_002', price = 100},
            {nameHash = 'FM_Tat_M_003', price = 100},
            {nameHash = 'FM_Tat_M_004', price = 100},
            {nameHash = 'FM_Tat_M_005', price = 100},
            {nameHash = 'FM_Tat_M_006', price = 100},
            {nameHash = 'FM_Tat_M_007', price = 100},
            {nameHash = 'FM_Tat_M_008', price = 100},
            {nameHash = 'FM_Tat_M_009', price = 100},
            {nameHash = 'FM_Tat_M_010', price = 100},
            {nameHash = 'FM_Tat_M_011', price = 100},
            {nameHash = 'FM_Tat_M_012', price = 100},
            {nameHash = 'FM_Tat_M_013', price = 100},
            {nameHash = 'FM_Tat_M_014', price = 100},
            {nameHash = 'FM_Tat_M_015', price = 100},
            {nameHash = 'FM_Tat_M_016', price = 100},
            {nameHash = 'FM_Tat_M_017', price = 100},
            {nameHash = 'FM_Tat_M_018', price = 100},
            {nameHash = 'FM_Tat_M_019', price = 100},
            {nameHash = 'FM_Tat_M_020', price = 100},
            {nameHash = 'FM_Tat_M_021', price = 100},
            {nameHash = 'FM_Tat_M_022', price = 100},
            {nameHash = 'FM_Tat_M_023', price = 100},
            {nameHash = 'FM_Tat_M_024', price = 100},
            {nameHash = 'FM_Tat_M_025', price = 100},
            {nameHash = 'FM_Tat_M_026', price = 100},
            {nameHash = 'FM_Tat_M_027', price = 100},
            {nameHash = 'FM_Tat_M_028', price = 100},
            {nameHash = 'FM_Tat_M_029', price = 100},
            {nameHash = 'FM_Tat_M_030', price = 100},
            {nameHash = 'FM_Tat_M_031', price = 100},
            {nameHash = 'FM_Tat_M_032', price = 100},
            {nameHash = 'FM_Tat_M_033', price = 100},
            {nameHash = 'FM_Tat_M_034', price = 100},
            {nameHash = 'FM_Tat_M_035', price = 100},
            {nameHash = 'FM_Tat_M_036', price = 100},
            {nameHash = 'FM_Tat_M_037', price = 100},
            {nameHash = 'FM_Tat_M_038', price = 100},
            {nameHash = 'FM_Tat_M_039', price = 100},
            {nameHash = 'FM_Tat_M_040', price = 100},
            {nameHash = 'FM_Tat_M_041', price = 100},
            {nameHash = 'FM_Tat_M_042', price = 100},
            {nameHash = 'FM_Tat_M_043', price = 100},
            {nameHash = 'FM_Tat_M_044', price = 100},
            {nameHash = 'FM_Tat_M_045', price = 100},
            {nameHash = 'FM_Tat_M_046', price = 100},
            {nameHash = 'FM_Tat_M_047', price = 100},
            {nameHash = 'FM_Tat_F_000', price = 100},
            {nameHash = 'FM_Tat_F_001', price = 100},
            {nameHash = 'FM_Tat_F_002', price = 100},
            {nameHash = 'FM_Tat_F_003', price = 100},
            {nameHash = 'FM_Tat_F_004', price = 100},
            {nameHash = 'FM_Tat_F_005', price = 100},
            {nameHash = 'FM_Tat_F_006', price = 100},
            {nameHash = 'FM_Tat_F_007', price = 100},
            {nameHash = 'FM_Tat_F_008', price = 100},
            {nameHash = 'FM_Tat_F_009', price = 100},
            {nameHash = 'FM_Tat_F_010', price = 100},
            {nameHash = 'FM_Tat_F_011', price = 100},
            {nameHash = 'FM_Tat_F_012', price = 100},
            {nameHash = 'FM_Tat_F_013', price = 100},
            {nameHash = 'FM_Tat_F_014', price = 100},
            {nameHash = 'FM_Tat_F_015', price = 100},
            {nameHash = 'FM_Tat_F_016', price = 100},
            {nameHash = 'FM_Tat_F_017', price = 100},
            {nameHash = 'FM_Tat_F_018', price = 100},
            {nameHash = 'FM_Tat_F_019', price = 100},
            {nameHash = 'FM_Tat_F_020', price = 100},
            {nameHash = 'FM_Tat_F_021', price = 100},
            {nameHash = 'FM_Tat_F_022', price = 100},
            {nameHash = 'FM_Tat_F_023', price = 100},
            {nameHash = 'FM_Tat_F_024', price = 100},
            {nameHash = 'FM_Tat_F_025', price = 100},
            {nameHash = 'FM_Tat_F_026', price = 100},
            {nameHash = 'FM_Tat_F_027', price = 100},
            {nameHash = 'FM_Tat_F_028', price = 100},
            {nameHash = 'FM_Tat_F_029', price = 100},
            {nameHash = 'FM_Tat_F_030', price = 100},
            {nameHash = 'FM_Tat_F_031', price = 100},
            {nameHash = 'FM_Tat_F_032', price = 100},
            {nameHash = 'FM_Tat_F_033', price = 100},
            {nameHash = 'FM_Tat_F_034', price = 100},
            {nameHash = 'FM_Tat_F_035', price = 100},
            {nameHash = 'FM_Tat_F_036', price = 100},
            {nameHash = 'FM_Tat_F_037', price = 100},
            {nameHash = 'FM_Tat_F_038', price = 100},
            {nameHash = 'FM_Tat_F_039', price = 100},
            {nameHash = 'FM_Tat_F_040', price = 100},
            {nameHash = 'FM_Tat_F_041', price = 100},
            {nameHash = 'FM_Tat_F_042', price = 100},
            {nameHash = 'FM_Tat_F_043', price = 100},
            {nameHash = 'FM_Tat_F_044', price = 100},
            {nameHash = 'FM_Tat_F_045', price = 100},
            {nameHash = 'FM_Tat_F_046', price = 100},
            {nameHash = 'FM_Tat_F_047', price = 100},
            {nameHash = 'FM_F_Hair_003_a', price = 100},
            {nameHash = 'FM_F_Hair_003_b', price = 100},
            {nameHash = 'FM_F_Hair_003_c', price = 100},
            {nameHash = 'FM_F_Hair_003_d', price = 100},
            {nameHash = 'FM_F_Hair_003_e', price = 100},
            {nameHash = 'FM_F_Hair_005_a', price = 100},
            {nameHash = 'FM_F_Hair_005_b', price = 100},
            {nameHash = 'FM_F_Hair_005_c', price = 100},
            {nameHash = 'FM_F_Hair_005_d', price = 100},
            {nameHash = 'FM_F_Hair_005_e', price = 100},
            {nameHash = 'FM_F_Hair_006_a', price = 100},
            {nameHash = 'FM_F_Hair_006_b', price = 100},
            {nameHash = 'FM_F_Hair_006_c', price = 100},
            {nameHash = 'FM_F_Hair_006_d', price = 100},
            {nameHash = 'FM_F_Hair_006_e', price = 100},
            {nameHash = 'FM_F_Hair_013_a', price = 100},
            {nameHash = 'FM_F_Hair_013_b', price = 100},
            {nameHash = 'FM_F_Hair_013_c', price = 100},
            {nameHash = 'FM_F_Hair_013_d', price = 100},
            {nameHash = 'FM_F_Hair_013_e', price = 100},
            {nameHash = 'FM_F_Hair_014_a', price = 100},
            {nameHash = 'FM_F_Hair_014_b', price = 100},
            {nameHash = 'FM_F_Hair_014_c', price = 100},
            {nameHash = 'FM_F_Hair_014_d', price = 100},
            {nameHash = 'FM_F_Hair_014_e', price = 100},
            {nameHash = 'FM_F_Hair_long_a', price = 100},
            {nameHash = 'FM_F_Hair_long_b', price = 100},
            {nameHash = 'FM_F_Hair_long_c', price = 100},
            {nameHash = 'FM_F_Hair_long_d', price = 100},
            {nameHash = 'FM_F_Hair_long_e', price = 100},
            {nameHash = 'FM_M_Hair_001_a', price = 100},
            {nameHash = 'FM_M_Hair_001_b', price = 100},
            {nameHash = 'FM_M_Hair_001_c', price = 100},
            {nameHash = 'FM_M_Hair_001_d', price = 100},
            {nameHash = 'FM_M_Hair_001_e', price = 100},
            {nameHash = 'FM_M_Hair_003_a', price = 100},
            {nameHash = 'FM_M_Hair_003_b', price = 100},
            {nameHash = 'FM_M_Hair_003_c', price = 100},
            {nameHash = 'FM_M_Hair_003_d', price = 100},
            {nameHash = 'FM_M_Hair_003_e', price = 100},
            {nameHash = 'FM_M_Hair_006_a', price = 100},
            {nameHash = 'FM_M_Hair_006_b', price = 100},
            {nameHash = 'FM_M_Hair_006_c', price = 100},
            {nameHash = 'FM_M_Hair_006_d', price = 100},
            {nameHash = 'FM_M_Hair_006_e', price = 100},
            {nameHash = 'FM_M_Hair_008_a', price = 100},
            {nameHash = 'FM_M_Hair_008_b', price = 100},
            {nameHash = 'FM_M_Hair_008_c', price = 100},
            {nameHash = 'FM_M_Hair_008_d', price = 100},
            {nameHash = 'FM_M_Hair_008_e', price = 100},
            {nameHash = 'FM_M_Hair_long_a', price = 100},
            {nameHash = 'FM_M_Hair_long_b', price = 100},
            {nameHash = 'FM_M_Hair_long_c', price = 100},
            {nameHash = 'FM_M_Hair_long_d', price = 100},
            {nameHash = 'FM_M_Hair_long_e', price = 100},
            {nameHash = 'NG_M_Hair_001', price = 100},
            {nameHash = 'NG_M_Hair_002', price = 100},
            {nameHash = 'NG_M_Hair_003', price = 100},
            {nameHash = 'NG_M_Hair_004', price = 100},
            {nameHash = 'NG_M_Hair_005', price = 100},
            {nameHash = 'NG_M_Hair_006', price = 100},
            {nameHash = 'NG_M_Hair_007', price = 100},
            {nameHash = 'NG_M_Hair_008', price = 100},
            {nameHash = 'NG_M_Hair_009', price = 100},
            {nameHash = 'NG_M_Hair_010', price = 100},
            {nameHash = 'NG_M_Hair_011', price = 100},
            {nameHash = 'NG_M_Hair_012', price = 100},
            {nameHash = 'NG_M_Hair_013', price = 100},
            {nameHash = 'NG_M_Hair_014', price = 100},
            {nameHash = 'NG_M_Hair_015', price = 100},
            {nameHash = 'NGBea_M_Hair_000', price = 100},
            {nameHash = 'NGBea_M_Hair_001', price = 100},
            {nameHash = 'NGBus_M_Hair_000', price = 100},
            {nameHash = 'NGBus_M_Hair_001', price = 100},
            {nameHash = 'NGHip_M_Hair_000', price = 100},
            {nameHash = 'NGHip_M_Hair_001', price = 100},
            {nameHash = 'NGInd_M_Hair_000', price = 100},
            {nameHash = 'NG_F_Hair_001', price = 100},
            {nameHash = 'NG_F_Hair_002', price = 100},
            {nameHash = 'NG_F_Hair_003', price = 100},
            {nameHash = 'NG_F_Hair_004', price = 100},
            {nameHash = 'NG_F_Hair_005', price = 100},
            {nameHash = 'NG_F_Hair_006', price = 100},
            {nameHash = 'NG_F_Hair_007', price = 100},
            {nameHash = 'NG_F_Hair_008', price = 100},
            {nameHash = 'NG_F_Hair_009', price = 100},
            {nameHash = 'NG_F_Hair_010', price = 100},
            {nameHash = 'NG_F_Hair_011', price = 100},
            {nameHash = 'NG_F_Hair_012', price = 100},
            {nameHash = 'NG_F_Hair_013', price = 100},
            {nameHash = 'NG_F_Hair_014', price = 100},
            {nameHash = 'NG_F_Hair_015', price = 100},
            {nameHash = 'NGBea_F_Hair_000', price = 100},
            {nameHash = 'NGBea_F_Hair_001', price = 100},
            {nameHash = 'NGBus_F_Hair_000', price = 100},
            {nameHash = 'NGBus_F_Hair_001', price = 100},
            {nameHash = 'NGHip_F_Hair_000', price = 100},
            {nameHash = 'NGHip_F_Hair_001', price = 100},
            {nameHash = 'NGInd_F_Hair_000', price = 100}
        },
    },
    TattooCategories = {
        {name = "Tatouages chics", value = 'mpbusiness_overlays'},
        {name = "Tatouages hippies", value = 'mphipster_overlays'},
        {name = "Tatouages biker", value = 'mpbiker_overlays'},
        {name = "Tatouages aviateurs", value = 'mpairraces_overlays'},
        {name = "Tatouages plages", value = 'mpbeach_overlays'},
        {name = "Tatouages noël", value = 'mpchristmas2_overlays'},
        {name = "Tatouages pilotes", value = 'mpgunrunning_overlays'},
        {name = "Tatouages import", value = 'mpimportexport_overlays'},
        {name = "Tatouages lowrider", value = 'mplowrider2_overlays'},
        {name = "Tatouages religieux", value = 'mplowrider_overlays'},
        {name = "Tatouages noël 2017", value = 'mpchristmas2017_overlays'},
        {name = "Tatouages Braquage", value = 'mpheist3_overlays'},
        {name = "Tatouages Braquage 2", value = 'mpheist4_overlays'},
        {name = "Tatouages Luxe", value = 'mpluxe_overlays'},
        {name = "Tatouages Luxe 2", value = 'mpluxe2_overlays'},
        {name = "Tatouages Contrebande", value = 'mpsmuggler_overlays'},
        {name = "Tatouages Cascadeur", value = 'mpstunt_overlays'},
        {name = "Tatouages Vinewood", value = 'mpvinewood_overlays'},
        {name = "Tatouages Multijoueur", value = 'multiplayer_overlays'},
    },
}


local Tatouage = {}
local playerTatoos = {}
local currentPreviewTatoo = nil
local cleaning = false
function ShowHelpNotification(msg)
    AddTextEntry('HelpNotification', msg)
	BeginTextCommandDisplayHelp('HelpNotification')
    EndTextCommandDisplayHelp(0, false, true, -1)
end

RegisterNetEvent("SneakyLife:buyTattoo")
AddEventHandler("SneakyLife:buyTattoo", function(ok)
    if ok then
        RageUI.Popup({message = "~g~Tatouage acheté"})
    else
        RageUI.Popup({message = "~r~Vous n'avez pas assez d'argent!"})
    end
end)

RegisterNetEvent("SneakyLife:tatoesCallback")
AddEventHandler("SneakyLife:tatoesCallback", function(ok)
    if ok ~= nil then
        playerTatoos = json.decode(ok)
        ClearPedDecorations(PlayerPedId())
        for _,t in pairs(playerTatoos) do
            AddPedDecorationFromHashes(PlayerPedId(),t.cat,t.name) 
        end
    end
end)

local firstLoad = false

AddEventHandler("Sneakyskinchanger:loadSkin", function(skin)
	if not firstLoad then
		Citizen.CreateThread(function()
			while not GetEntityModel(PlayerPedId() == `mp_m_freemode_01` or GetEntityModel(PlayerPedId()) == `mp_f_freemode_01`) do
				Citizen.Wait(10)
			end

			Citizen.Wait(75)
			SneakyEvent("SneakyLife:requestPlayerTatoos")
            SneakyEvent("SneakyClothesGetHairFade")
		end)
		
		firstLoad = true
	else
		Citizen.Wait(75)

		for _,t in pairs(playerTatoos) do
			AddPedDecorationFromHashes(PlayerPedId(),t.cat,t.name) 
		end
	end
end)



RegisterNetEvent("SneakyLife:clean")
AddEventHandler("SneakyLife:clean", function(ok)
    if ok then
        playerTatoos = {}
        DoScreenFadeOut(1000)
        while not IsScreenFadedOut() do Citizen.Wait(10) end
        ClearPedDecorations(PlayerPedId())
        Citizen.Wait(200)
        DoScreenFadeIn(1000)
        cleaning = false
        RageUI.Popup({message = "~g~Tous vos tatouages ont étés effacés"})
    else
        RageUI.Popup({message = "~r~Vous n'avez pas assez d'argent!"})
    end
end)

RMenu.Add('tattoo', 'main', RageUI.CreateMenu("", "~r~Sélectionnez une catégorie", 10, 200,'shopui_title_tattoos4', 'shopui_title_tattoos4'))
for k,v in pairs(TattooShop.TattooCategories) do
    RMenu.Add('tattoo', 'part'..k, RageUI.CreateSubMenu(RMenu:Get('tattoo', 'main'), "", "~b~Sélectionnez votre tatouage"))
    RMenu:Get('tattoo', 'part'..k).Closed = function()
        ClearPedDecorations(PlayerPedId())
        for _,t in pairs(playerTatoos) do
            ApplyPedOverlay(PlayerPedId(),t.cat,t.name) 
        end
    end
end
RMenu:Get('tattoo', 'main').EnableMouse = false

RMenu:Get('tattoo', 'main').Closed = function()
    ESX.TriggerServerCallback('Sneakyesx_skin:getPlayerSkin', function(skin, jobSkin)
        local isMale = skin.sex == 0
        TriggerEvent('Sneakyskinchanger:loadDefaultModel', isMale, function()
            ESX.TriggerServerCallback('Sneakyesx_skin:getPlayerSkin', function(skin)
            TriggerEvent('Sneakyskinchanger:loadSkin', skin)
            TriggerEvent('Sneakyesx:restoreLoadout')
            end)
        end)
    end)
    ClearPedDecorations(PlayerPedId())
    for _,t in pairs(playerTatoos) do
        ApplyPedOverlay(PlayerPedId(),t.cat,t.name) 
    end
    FreezeEntityPosition(GetPlayerPed(-1), false)
    Tatouage.Menu = false 
end

function OpenTattooRageUIMenu()

    if Tatouage.Menu then
        Tatouage.Menu = false
    else
        Tatouage.Menu = true
        RageUI.Visible(RMenu:Get('tattoo', 'main'), true)

        Citizen.CreateThread(function()
			while Tatouage.Menu do
                FreezeEntityPosition(GetPlayerPed(-1), true)
                RageUI.IsVisible(RMenu:Get('tattoo', 'main'), true, false, true, function()
    
                    for k,v in pairs(TattooShop.TattooCategories) do
                        RageUI.Button(v.name, nil, { RightLabel = "→" }, true, function()
                        end, RMenu:Get('tattoo', 'part'..k))
                    end
                    RageUI.Button("~r~Effacer tous mes tatouages", nil, { RightLabel = "~g~1500$ ~s~→" }, not cleaning, function(Hovered, Active, Selected)
                        if (Selected) then
                            cleaning = true
                            SneakyEvent("SneakyLife:payClean")
                        end
                    end)
                end)
                for k,v in pairs(TattooShop.TattooCategories) do
                    RageUI.IsVisible(RMenu:Get('tattoo', 'part'..k), true, false, true, function()
                        RageUI.Button("~r~Supprimer la prévisualisation actuelle", nil, { RightLabel = "→" }, true, function(Hovered, Active, Selected)
                            if (Selected) then
                                ClearPedDecorations(PlayerPedId())
                                for _,t in pairs(playerTatoos) do
                                    ApplyPedOverlay(PlayerPedId(),t.cat,t.name) 
                                end
                            end
                        end)
                        for index,tatoo in pairs(TattooShop.TattooList[v.value]) do
                            RageUI.Button("Tatouage n°"..index, nil, { RightLabel = "~g~"..tatoo.price.."$ ~s~→" }, true, function(Hovered, Active, Selected)
                                if (Active) then
                                    if currentPreviewTatoo ~= GetHashKey(tatoo.nameHash) then 
                                        ClearPedDecorations(PlayerPedId())
                                        for _,t in pairs(playerTatoos) do
                                            ApplyPedOverlay(PlayerPedId(),t.cat,t.name) 
                                        end
                                        ApplyPedOverlay(PlayerPedId(),GetHashKey(TattooShop.TattooCategories[k].value),GetHashKey(tatoo.nameHash)) 
                                    end
                                    currentPreviewTatoo = GetHashKey(tatoo.nameHash)
                                end
                                if (Selected) then
                                    local needModif = true
                                    for _,t in pairs(playerTatoos) do
                                        if GetHashKey(TattooShop.TattooCategories[k].value) == playerTatoos.cat and GetHashKey(tatoo.nameHash) == playerTatoos.name then
                                            needModif = false
                                        end
                                    end
                                    if needModif then
                                        table.insert(playerTatoos, {cat = GetHashKey(TattooShop.TattooCategories[k].value), name = GetHashKey(tatoo.nameHash)})
                                        SneakyEvent("SneakyLife:pay", tatoo.price, playerTatoos)
                                    else
                                        RageUI.Popup({message = "~r~Vous possédez déjà ce tatouage!"})
                                    end
                                end
                            end)
                        end
                    end)
                end
				Wait(0)
			end
		end) 
	end
end

Citizen.CreateThread(function()
    while true do
        att = 500
        local pCoords = GetEntityCoords(PlayerPedId())
        for k,v in pairs(TattooShop.Position) do
            if not Tatouage.Menu then
                if #(pCoords-v.pos) < 10.0 then
                    att = 1
                
                    if #(pCoords-v.pos) < 1.5 then
                        ShowHelpNotification("Appuyez sur ~INPUT_PICKUP~ pour interagir avec le tatoueur")
                        if IsControlJustPressed(0, 51) then
                            if GetEntityModel(GetPlayerPed(-1)) == GetHashKey("mp_m_freemode_01") then
                                SetPedComponentVariation(GetPlayerPed(-1), 8, 15,0, 2)
                                SetPedComponentVariation(GetPlayerPed(-1), 11, 15,0, 2)
                                SetPedComponentVariation(GetPlayerPed(-1), 3, 15)
                                SetPedComponentVariation(GetPlayerPed(-1), 4, 14,0, 2)
                                SetPedComponentVariation(GetPlayerPed(-1), 6, 43,0, 2)
                                SetPedComponentVariation(ped, componentId, drawableId, textureId, paletteId)
                            else
                                SetPedComponentVariation(GetPlayerPed(-1), 8, 14,0, 2) --tshirt
                                SetPedComponentVariation(GetPlayerPed(-1), 11, 15,0, 2) --torse
                                SetPedComponentVariation(GetPlayerPed(-1), 3, 15) -- bras
                                SetPedComponentVariation(GetPlayerPed(-1), 4, 15,0, 2) --jambe
                                SetPedComponentVariation(GetPlayerPed(-1), 6, 41,0, 2) --chaussure
                            end
                            OpenTattooRageUIMenu()
                        end
                    end
                end
            end
        end
        Citizen.Wait(att)
    end
end)